### PR TITLE
Transforming SearchDreamTest into integration test

### PR DESCRIPTION
**Pull request by Cotel**
### :pushpin: References
* **Related pull-requests:** #21 

### :tophat: What is the goal?

Showing how to make integration tests with RestTemplate.

### :memo: How is it being implemented?

We need to have an user beforehand on the database, this is achieved thanks to import.sql file in resources which will be executed everytime before testing.

We need to add the Authorization header with the corresponding token on each request before being performed.

### :boom: How can it be tested?

This is a test by itself 😆 
 
### :floppy_disk: Requires DB migration?

- [x] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### CODE REVIEW

**Comment by Cotel** [comment]
Dunno why it isn't working. It says Connection refused but nothing more 🤔 .

**Comment by tonilopezmr** [comment]
One note my tests were integration test as well, but not with HTTP 👍

**Comment by Cotel** [comment]
Is this an E2E test then?

**Comment by Cotel** [comment]
I would like to have this branch merged for making an integration test for #27 soooo... 😇

**Comment by kevinzs** [comment]
@Cotel One question, with this when the test are running it's running with a normal local server or it's a test environment? I mean if it use the same database than local or have another one for testing.

**Comment by Cotel** [comment]
For now, we are using an H2 database which runs on memory and gets destroyed when the app stops. I've created an `import.sql` at `test/resources` which imports all the data before the tests start.

If you want to import data on your local environment when running the server (and not testint) you can create this file on `main/resources`.

**Review by kevinzs — APPROVED** [review]

**Review by Diphendara — APPROVED** [review]

**Comment by tonilopezmr** [comment]
yes, it is @Cotel

**Pull request merged**
