### PR TITLE
Fix variable names

### PR DESCRIPTION
**Pull request by Diphendara**
### :pushpin: References
* **Issue:** None
* **Related pull-requests:** None

### :tophat: What is the goal?

Fix names to be descriptive 
### :memo: How is it being implemented?

Just rename the variables
### :boom: How can it be tested?

-Can't be tested, is just a rename.
 
### :floppy_disk: Requires DB migration?

- [X] Nope, we can just merge this branch.
- [ ] Yes, but we need to apply it before merging this branch.
- [ ] Yes, it's already applied.

### CODE REVIEW

**Comment by Cotel** [comment]
This is not a hotfix. A hotfix is a branch which starts from `master` and ends there too. It solves some critical bug from production without passing through develop flow. This is like any other feature branch.

The new names are good 👌. But we have a chance here for using a `ObjectMother` pattern so we can simplify the creation of objects in determined situations:

```kotlin
val emptyTitleDreamRequest = DreamRequestObjectMother.emptyTitle()
``` 

You can make a branch refactoring existing tests with this pattern and improve them to be more declarative.

**Review by Cotel — APPROVED** [review]
Good work 💯

**Comment by Diphendara** [comment]
Then should I add the changes you say in a new branch with a different name and then I'll make a PR again?

**Comment by Diphendara** [comment]
@Cotel Then should I add the changes you say in a new branch with a different name and then I'll make a PR again?

**Comment by Cotel** [comment]
You can merge this branch and make a new one with the `ObjectMother` yes

**Pull request merged**
